services:
  detection:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /
    volumes:
      - ./env:/env
      - ./src:/src
      - ./clips:/clips
      - ./analysis:/analysis
    entrypoint: python3 /src/process_video.py
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
